---
- name: Install common packages
  ansible.builtin.import_tasks: packages.yml

- name: Configure timezone and time synchronization
  ansible.builtin.import_tasks: time.yml

- name: Harden sshd
  ansible.builtin.import_tasks: sshd.yml
